In [1]:
import cx_Oracle
import pandas as pd
from sklearn.preprocessing import StandardScaler
from datetime import datetime
from utils import helpers
import os

In [2]:
df=helpers.rebalancing_by_period('2021-01-01','2025-01-01',5)

In [3]:
df

['2021-01-04',
 '2021-01-11',
 '2021-01-18',
 '2021-01-25',
 '2021-02-01',
 '2021-02-08',
 '2021-02-22',
 '2021-03-01',
 '2021-03-08',
 '2021-03-15',
 '2021-03-22',
 '2021-03-29',
 '2021-04-06',
 '2021-04-13',
 '2021-04-20',
 '2021-04-27',
 '2021-05-07',
 '2021-05-14',
 '2021-05-21',
 '2021-05-28',
 '2021-06-04',
 '2021-06-11',
 '2021-06-21',
 '2021-06-28',
 '2021-07-05',
 '2021-07-12',
 '2021-07-19',
 '2021-07-26',
 '2021-08-02',
 '2021-08-09',
 '2021-08-16',
 '2021-08-23',
 '2021-08-30',
 '2021-09-06',
 '2021-09-13',
 '2021-09-22',
 '2021-09-29',
 '2021-10-13',
 '2021-10-20',
 '2021-10-27',
 '2021-11-03',
 '2021-11-10',
 '2021-11-17',
 '2021-11-24',
 '2021-12-01',
 '2021-12-08',
 '2021-12-15',
 '2021-12-22',
 '2021-12-29',
 '2022-01-06',
 '2022-01-13',
 '2022-01-20',
 '2022-01-27',
 '2022-02-10',
 '2022-02-17',
 '2022-02-24',
 '2022-03-03',
 '2022-03-10',
 '2022-03-17',
 '2022-03-24',
 '2022-03-31',
 '2022-04-11',
 '2022-04-18',
 '2022-04-25',
 '2022-05-05',
 '2022-05-12',
 '2022-05-19',
 '2022-05-26',
 '2022-06-02',
 '2022-06-10',
 '2022-06-17',
 '2022-06-24',
 '2022-07-01',
 '2022-07-08',
 '2022-07-15',
 '2022-07-22',
 '2022-07-29',
 '2022-08-05',
 '2022-08-12',
 '2022-08-19',
 '2022-08-26',
 '2022-09-02',
 '2022-09-09',
 '2022-09-19',
 '2022-09-26',
 '2022-10-10',
 '2022-10-17',
 '2022-10-24',
 '2022-10-31',
 '2022-11-07',
 '2022-11-14',
 '2022-11-21',
 '2022-11-28',
 '2022-12-05',
 '2022-12-12',
 '2022-12-19',
 '2022-12-26',
 '2023-01-03',
 '2023-01-10',
 '2023-01-17',
 '2023-01-31',
 '2023-02-07',
 '2023-02-14',
 '2023-02-21',
 '2023-02-28',
 '2023-03-07',
 '2023-03-14',
 '2023-03-21',
 '2023-03-28',
 '2023-04-04',
 '2023-04-12',
 '2023-04-19',
 '2023-04-26',
 '2023-05-08',
 '2023-05-15',
 '2023-05-22',
 '2023-05-29',
 '2023-06-05',
 '2023-06-12',
 '2023-06-19',
 '2023-06-28',
 '2023-07-05',
 '2023-07-12',
 '2023-07-19',
 '2023-07-26',
 '2023-08-02',
 '2023-08-09',
 '2023-08-16',
 '2023-08-23',
 '2023-08-30',
 '2023-09-06',
 '2023-09-13',
 '2023-09-20',
 '2023-09-27',
 '2023-10-12',
 '2023-10-19',
 '2023-10-26',
 '2023-11-02',
 '2023-11-09',
 '2023-11-16',
 '2023-11-23',
 '2023-11-30',
 '2023-12-07',
 '2023-12-14',
 '2023-12-21',
 '2023-12-28',
 '2024-01-05',
 '2024-01-12',
 '2024-01-19',
 '2024-01-26',
 '2024-02-02',
 '2024-02-19',
 '2024-02-26',
 '2024-03-04',
 '2024-03-11',
 '2024-03-18',
 '2024-03-25',
 '2024-04-01',
 '2024-04-10',
 '2024-04-17',
 '2024-04-24',
 '2024-05-06',
 '2024-05-13',
 '2024-05-20',
 '2024-05-27',
 '2024-06-03',
 '2024-06-11',
 '2024-06-18',
 '2024-06-25',
 '2024-07-02',
 '2024-07-09',
 '2024-07-16',
 '2024-07-23',
 '2024-07-30',
 '2024-08-06',
 '2024-08-13',
 '2024-08-20',
 '2024-08-27',
 '2024-09-03',
 '2024-09-10',
 '2024-09-19',
 '2024-09-26',
 '2024-10-10',
 '2024-10-17',
 '2024-10-24',
 '2024-10-31',
 '2024-11-07',
 '2024-11-14',
 '2024-11-21',
 '2024-11-28',
 '2024-12-05',
 '2024-12-12',
 '2024-12-19',
 '2024-12-26']

In [10]:
import os
print(os.getcwd())

/home/quant/zc/backtrader/QuantStockPicker

In [1]:
import numpy as np
import pandas as pd
import warnings

warnings.filterwarnings('ignore')
pd.options.display.float_format='{:.4%}'.format

In [4]:
start='2016-01-01'
end='2019-12-30'

assets=['AAPL']
assets.sort()

data=yf.download(assets,start=start,end=end)
data=data.loc[:,('Adj Close',slice(None))]
data.columns=assets

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAPL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

In [2]:
data=[
    ("S_VAL_PB_NEW","PB(市净率)","每股股价与每股净资产的比率"),
    ("S_VAL_PE_TTM","PE(市盈率)","每股股价与每股净资产的比率(静态), 算法：市盈率（PE，TTM）=总市值/净利润（TTM），其中：总市值=股价*总股本；总股本=A股股价*公司发行在外普通股总数（多地上市股份总和）")
]

In [3]:
df=pd.DataFrame(data,columns=["英文名称","中文名称","因子含义"])

In [4]:
df

           英文名称     中文名称                                               因子含义
0  S_VAL_PB_NEW  PB(市净率)                                      每股股价与每股净资产的比率
1  S_VAL_PE_TTM  PE(市盈率)  每股股价与每股净资产的比率(静态), 算法：市盈率（PE，TTM）=总市值/净利润（TTM）...

In [5]:
df.to_csv("utils/factor.csv",index=False,encoding="utf_8_sig")

In [6]:
df1=pd.read_csv("utils/factor.csv")

In [7]:
df1

           英文名称     中文名称                                               因子含义
0  S_VAL_PB_NEW  PB(市净率)                                      每股股价与每股净资产的比率
1  S_VAL_PE_TTM  PE(市盈率)  每股股价与每股净资产的比率(静态), 算法：市盈率（PE，TTM）=总市值/净利润（TTM）...

In [9]:
for index,row in df1.iterrows():
    englist_name=row['英文名称']
    combined_info=f"因子名称:{row['中文名称']},因子含义:{row['因子含义']}"
    
    print(englist_name)
    print(combined_info)

S_VAL_PB_NEW
因子名称:PB(市净率),因子含义:每股股价与每股净资产的比率
<class 'str'>
<class 'str'>
S_VAL_PE_TTM
因子名称:PE(市盈率),因子含义:每股股价与每股净资产的比率(静态), 算法：市盈率（PE，TTM）=总市值/净利润（TTM），其中：总市值=股价*总股本；总股本=A股股价*公司发行在外普通股总数（多地上市股份总和）
<class 'str'>
<class 'str'>

In [15]:
project_root = os.getcwd()  #获取当前目录路径
path_name="prem_value"

In [16]:
res_path=os.path.join(project_root,"result",path_name)

In [18]:
res_path

'/home/quant/zc/backtrader/QuantStockPicker/result/prem_value'

In [19]:
from pathlib import Path
py_file=Path(res_path)/f"{englist_name}.py"
py_file

PosixPath('/home/quant/zc/backtrader/QuantStockPicker/result/prem_value/S_VAL_PE_TTM.py')